[tool.poetry]
name = "realsense-align"
version = "0.1.0"
description = "Python realsense align"
authors = ["Louie Lu <git@louie.lu>"]
license = "BSD 3-Clause Clear License"
readme = "README.md"
packages = [{include = "realsense_align", from = "src" }]


[tool.poetry.build]
script = "build_ext.py"
generate-setup-file = true

[tool.poetry.dependencies]
python = "^3.8"
pybind11 = "^2.10.4"
numpy = "^1.24.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
matplotlib = "^3.7.1"
opencv-python = "^4.7.0.72"
line-profiler = "^4.0.3"
pre-commit = "^3.3.3"

[build-system]
requires = ["poetry>=1.1.0", "setuptools", "wheel", "pybind11>=2.10.4"]
build-backend = "poetry.masonry.api"
