name: ci

on:
  [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "true"

      - if: ${{ matrix.os == 'macos-latest' }}
        run:
          |
            brew install llvm libomp
            export CC=/usr/local/opt/llvm/bin/clang

      - name: Setup
        run:
          |
            python -m pip install --upgrade pip setuptools wheel
            python -m pip install poetry
            poetry install -vvv
      - name: Build
        run:
          |
            poetry build
