name: OpenMP macOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install LLVM (for OpenMP support)
      run: brew install llvm

    - name: Set up environment variables
      run: |
        echo "PATH=$(brew --prefix llvm)/bin:$PATH" >> $GITHUB_ENV
        echo "LDFLAGS=-L$(brew --prefix llvm)/lib" >> $GITHUB_ENV
        echo "CPPFLAGS=-I$(brew --prefix llvm)/include" >> $GITHUB_ENV

    - name: Create a sample OpenMP program
      run: |
        cat <<EOF > hello_omp.cpp
        #include <iostream>
        #include <omp.h>

        int main() {
            #pragma omp parallel
            {
                int thread_id = omp_get_thread_num();
                std::cout << "Hello from thread " << thread_id << std::endl;
            }
            return 0;
        }
        EOF

    - name: Compile with OpenMP
      run: clang++ -std=c++11 -fopenmp hello_omp.cpp -o hello_omp

    - name: Run the executable
      run: ./hello_omp
